export const platformType = {
    Null: 1,
    Undefined: 2,
    PrimitiveString: 10,
    PrimitiveNumber: 11,
    PrimitiveBoolean: 12,
    PrimitiveBigInt: 13,
    PrimitiveSymbol: 14,

    Function: 100,
    AsyncFunction: 101,
    GeneratorFunction: 102,

    Object: 1000,
    Set: 1002,
    Map: 1003,
    Date: 1004,
    RegExp: 1005,
    Promise: 1006,
    WeakMap: 1007,
    WeakSet: 1008,
    DataView: 1010,
    ReadableStream: 1011,
    WritableStream: 1012,
    ByteLengthQueuingStrategy: 1013,
    CountQueuingStrategy: 1014,
    TransformStream: 1015,

    Error: 1100,
    TypeError: 1101,
    RangeError: 1102,
    SyntaxError: 1103,
    URIError: 1104,
    ReferenceError: 1105,
    EvalError: 1106,
    AggregateError: 1107,

    Buffer: 1200,
    ArrayBuffer: 1201,
    SharedArrayBuffer: 1202,

    String: 1300,
    Number: 1301,
    Boolean: 1302,
    BigInt: 1303,
    Symbol: 1304,

    Array: 2000,

    Int8Array: 2001,
    Uint8Array: 2002,
    Uint8ClampedArray: 2003,
    Int16Array: 2004,
    Uint16Array: 2005,
    Int32Array: 2006,
    Uint32Array: 2007,
    Float32Array: 2008,
    Float64Array: 2009,
    BigInt64Array: 2010,
    BigUint64Array: 2011,

    RefData: 3000,

    ParentObject: 9000,
    ChildObject: 9001,
    Primitive: 9002,
    NullOrUndefined: 9003,
};
export const jsonTypes = {
    null: "null",
    undefined: "undefined",
    string: "string",
    object: "object",
    number: "number",
    boolean: "boolean",
    array: "array",
};
export const jsonTypeGroups = {
    primitive: [jsonTypes.string, jsonTypes.number, jsonTypes.boolean],
    reference: [jsonTypes.object, jsonTypes.array],
    exist: [jsonTypes.null, jsonTypes.string, jsonTypes.number, jsonTypes.boolean, jsonTypes.object, jsonTypes.array],
    effective: [jsonTypes.string, jsonTypes.number, jsonTypes.boolean, jsonTypes.object, jsonTypes.array],
    empty: [jsonTypes.null, jsonTypes.undefined],
    all: Object.values(jsonTypes),
};

export const typeofTypes = {
    null: "null",
    undefined: "undefined",
    string: "string",
    object: "object",
    number: "number",
    boolean: "boolean",
    array: "array",
    bigint: "bigint",
    symbol: "symbol",
    function: "function",
};
export const typeofTypeGroups = {
    primitive: [typeofTypes.string, typeofTypes.number, typeofTypes.boolean, typeofTypes.bigint, typeofTypes.symbol],
    reference: [typeofTypes.object, typeofTypes.array, typeofTypes.function],
    exist: [
        typeofTypes.null,
        typeofTypes.string,
        typeofTypes.number,
        typeofTypes.boolean,
        typeofTypes.bigint,
        typeofTypes.symbol,
        typeofTypes.object,
        typeofTypes.array,
        typeofTypes.function,
    ],
    effective: [
        typeofTypes.string,
        typeofTypes.number,
        typeofTypes.boolean,
        typeofTypes.bigint,
        typeofTypes.symbol,
        typeofTypes.object,
        typeofTypes.array,
        typeofTypes.function,
    ],
    empty: [typeofTypes.null, typeofTypes.undefined],
    all: Object.values(typeofTypes),
};
