import {
    create,
    enterContext,
    backContext,
    getParentInstance,
    getSiblingSchemaRefData,
    getSiblingInstanceRefData,
    getParentSchema,
    canEqualInstance,
    unlock,
    lock,
    clone,
    setCache,
    clearCache,
    getCache,
} from "./manage.mjs";
export const contextManage = {
    create,
    enterContext,
    backContext,
    getParentInstance,
    getSiblingSchemaRefData,
    getSiblingInstanceRefData,
    getParentSchema,
    canEqualInstance,
    unlock,
    lock,
    clone,
    setCache,
    clearCache,
    getCache,
};
