import {
    create,
    enterContext,
    backContext,
    getParentInstance,
    getSiblingSchemaRefData,
    getSiblingInstanceRefData,
    getParentSchema,
    canEqualInstance,
    unlock,
    lock,
    clone,
} from "./manage.mjs";
export const contextManage = {
    create,
    enterContext,
    backContext,
    getParentInstance,
    getSiblingSchemaRefData,
    getSiblingInstanceRefData,
    getParentSchema,
    canEqualInstance,
    unlock,
    lock,
    clone,
};
